criação da pagina de cadastro de jogador e componentes
lucanevess87/fute-app pull request #4
Opened 2023-09-06 02:18 UTC by EduTeles13

Criei a página de cadastro de jogadores só, tinha criado uns componentes mas aí achei tudo no chakra e excluí, então acho que não fiz nenhum componente à mais.

2023-09-07 20:37 UTC, lucanevess87 requested changes

2023-09-07 20:37 UTC, lucanevess87 commented on src/modules/public/Login/Login.tsx
> +        <TextInput label="E-mail" placeholder="Digite seu e-mail" borderRadius="md" width="21rem" />
Tava falando com breno sobre isso, quando tu coloca width fixa nos componentes tu deixa e estrutura muito rígida e presa ao tamanho de tela que tu tas vendo enquanto faz o codigo. Por default os componentes do Chakra já vem com width 100%, ou seja tu não precisa nem botar width e isso vai deixar o componente flexivel para diferentes telas. Se a tela aumentar a largura o componente aumenta e se diminuir ele diminui

2023-09-07 20:37 UTC, lucanevess87 commented on src/modules/public/Login/Login.tsx
> +        <LoginButton label="Entrar" borderRadius="md" width="5rem" marginLeft="7.75rem" />
tu consegue deslocar o botão mais para o canto colocando ele numa flex e dizendo que ele fica no justify-content: flex-end

2023-09-07 20:37 UTC, lucanevess87 commented on src/modules/public/Login/Login.tsx
> +        <TextInput label="Senha" placeholder="Digite a sua senha" borderRadius="md" width="21rem" />
Fazer formulário com react hook form

2023-09-07 20:37 UTC, lucanevess87 commented on src/pages/newpelada/index.tsx
> +      <NewPelada />
o nome da pasta que tem esse arquivo index tem que ser em portugues, porque esse nome vai para a url do navegador. Ingles tu bota no modulo, que nem tu ja faz. Nesse cado ficaria pages/nova-pelada/index.ts

2023-09-07 20:37 UTC, lucanevess87 commented on src/modules/public/NewPelada/NewPelada.tsx
> +        marginLeft="17rem"
cuidado com essas margins, paddiings com valores altos assim. Tenta posicionar o elemente usando Flex ou Grid

2023-09-08 11:48 UTC, EduTeles13 commented on src/modules/public/Login/Login.tsx
> +        <TextInput label="E-mail" placeholder="Digite seu e-mail" borderRadius="md" width="21rem" />
Ajustado.

2023-09-08 11:49 UTC, EduTeles13 commented on src/modules/public/Login/Login.tsx
> +        <LoginButton label="Entrar" borderRadius="md" width="5rem" marginLeft="7.75rem" />
Ajustado

2023-09-08 11:56 UTC, EduTeles13 commented on src/pages/newpelada/index.tsx
> +      <NewPelada />
feito

2023-09-10 01:56 UTC, merged